[tool.poetry]
name = "valory"
version = "2.0.0"
description = "Validated types for Python."
authors = ["user <user@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
